#!/bin/sh
# actualizador de paguetes para Debian
# actualizar.sh Programado en shell
# boton derecho para dar permisos del ejecucion o desde consola teclemaos: chmod 777 actualizar
# se ejecuta en consola ./actualizar
# Antonio Taboada
# 3 Sept 2016
echo 
echo "Actualizando Linux..."
echo
dpkg --configure -a
echo "Actualizando..."
apt-get clean
echo "Actualizando..."
apt-get update
echo "Actualizando..."
apt-get upgrade --fix-missing -y
echo "Actualizando..."
apt-get dist-upgrade -y
echo "Actualizando..."
apt-get autoremove -y
echo "Linux actualizado."
echo
